# Generated by Django 3.0.7 on 2020-07-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200702_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Delievery', 'Out for Delievery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
